version: 2
jobs:
    build:
        docker:
            - image: circleci/php:7.4-node-browsers
        

        steps:
            - checkout

            - run:
                name: "Prepare Environment"
                command: |
                    sudo apt update
                    sudo docker-php-ext-install zip

            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "composer.lock" }}
                    - v1-dependencies-

            - run:
                name: "Install Dependencies"
                command: composer install -n --prefer-dist

            - save_cache:
                key: composer-v1-{{ checksum "composer.lock" }}
                paths:
                    - vendor
            
            - run:
                name: "Create Environment File and Generate Key"
                command: |
                    mv .env.testing .env
                    php artisan key:generate

            - run:
                name: "Run Tests"
                command: ./vendor/bin/phpunit
            
            - store_test_results:
                path: tests/
        
            - store_artifacts:
                path: tests/